
#ifndef TTSFML_WINDOW_EXPORT_HPP
#define TTSFML_WINDOW_EXPORT_HPP

#include "Config.hpp"

#if defined(tinySFML_Window_EXPORTS)

#define TTSFML_WINDOW_API TTSFML_API_EXPORT

#else

#define TTSFML_WINDOW_API TTSFML_API_IMPORT

#endif

#endif // TTSFML_WINDOW_EXPORT_HPP